apiVersion: v1
kind: Service
metadata:
  name: garou-health
  namespace: garou
  labels:
    app: garou
    component: server
spec:
  type: ClusterIP
  selector:
    app: garou
    component: server
  ports:
    - name: health
      port: 9090
      targetPort: 9090
      protocol: TCP
